name: tawsella_final
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0

  intl_phone_field: ^3.2.0
  get: ^4.6.6
  http: ^1.2.1
  geolocator: ^7.6.2
  shared_preferences: ^2.0.0 
  validators: ^3.0.0
  url_launcher: ^6.0.19
  flutter_spinkit: ^5.2.0
  flutter_screenutil: ^5.7.0  
  google_maps_flutter: ^2.9.0
  easy_loading_button: ^0.3.2
  loading_btn: ^1.0.3
  web_socket_channel: ^3.0.1
  audioplayers: ^6.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
flutter:

  uses-material-design: true

  assets:
    - images/
    - assets/
    - assets/images/
    - assets/sound/notification.mp3

  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/Cairo-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
